knpu_oauth2_client:
    clients:
        forty_two:
            type: generic
            client_id: '%env(OAUTH_42_ID)%'
            client_secret: '%env(OAUTH_42_SECRET)%'
            redirect_route: auth_callback
            provider_class: League\OAuth2\Client\Provider\GenericProvider
            provider_options:
                urlAuthorize: 'https://api.intra.42.fr/oauth/authorize'
                urlAccessToken: 'https://api.intra.42.fr/oauth/token'
                urlResourceOwnerDetails: 'https://api.intra.42.fr/v2/me'
                scopes: ['public']
