# config/packages/security.yaml
security:
    # Password hashing (not used directly for OAuth, but required by Symfony)
    password_hashers:
        App\Entity\User: 'auto'

    # User provider using Doctrine and the User entity
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Firewalls define how users are authenticated
    firewalls:
        dev:
            # Disable security for profiler/debug tools
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Allow anonymous users (important!)
            anonymous: true

            # Our custom OAuth2 authenticator
            custom_authenticator:
                - App\Security\AppAuthenticator

            # Logout configuration
            logout:
                path: app_logout
                target: app_home

    # Access control rules
    access_control:
        # Allow anonymous access to the home page (welcome page)
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # Allow public access to login and OAuth callback
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/callback, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # Require login for all other routes
        - { path: ^/, roles: ROLE_USER }
