# config/packages/security.yaml
security:
    # Password hashing
    password_hashers:
        App\Entity\User: 'auto'

    # User provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\AppAuthenticator
            logout:
                path: app_logout
                target: app_home

    # Access control
    access_control:
        # Anonymous access to home page
        - { path: ^/$, allow_if: "is_granted('IS_AUTHENTICATED_ANONYMOUSLY')" }

        # Anonymous access to login & callback
        - { path: ^/login, allow_if: "is_granted('IS_AUTHENTICATED_ANONYMOUSLY')" }
        - { path: ^/auth/callback, allow_if: "is_granted('IS_AUTHENTICATED_ANONYMOUSLY')" }

        # Require login for all other routes
        - { path: ^/, roles: ROLE_USER }
