# config/packages/security.yaml
security:
    # Password hashing (not used directly for OAuth, but required by Symfony)
    password_hashers:
        App\Entity\User: 'auto'

    # User provider using Doctrine and the User entity
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Firewalls define how users are authenticated
    firewalls:
        dev:
            # Disable security for profiler/debug tools
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Our custom OAuth2 authenticator
            custom_authenticator:
                - App\Security\AppAuthenticator

            # Logout configuration
            logout:
                path: /logout          # URL, not route name
                target: /              # Redirect after logout
                # Allow GET for simplicity
                invalidate_session: true

    # Access control rules
    access_control:
        # Allow public access to login and OAuth callback
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/auth/callback, roles: PUBLIC_ACCESS }

        # Restrict all other routes to authenticated users
        - { path: ^/, roles: PUBLIC_ACCESS }