# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Use your custom OAuth2 authenticator
            custom_authenticators:
                - App\Security\AppAuthenticator

            # Set the authenticator as the entry point for login
            entry_point: App\Security\AppAuthenticator

            logout:
                path: app_logout
                target: app_home

    access_control:
        # Anonymous users can access home page
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # All other routes require login
        - { path: ^/, roles: ROLE_USER }
