security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\AppAuthenticator
            logout:
                path: app_logout
                target: app_home
            # No need for 'anonymous' or 'allow_if'

    access_control:
        # Require login for everything except login routes and OAuth callback
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/callback, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # All other routes require ROLE_USER
        - { path: ^/, roles: ROLE_USER }
